services:
  # --- Database for User Service ---
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: users_db
      MYSQL_TCP_PORT: 3306
    ports: ["3306:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpw"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  # --- Database for Team & Task Services ---
  mongo_db:
    image: mongo:7
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # --- User Service ---
  user_service:
    build: ./user_service
    container_name: user_service
    env_file:
      - ./.env 
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["8001:8001"]
    volumes:
      - ./user_service:/app
      - user_avatars:/app/user_avatars 
    restart: unless-stopped

  # --- Team Service ---
  team_service:
    build: ./team_service
    container_name: team_service
    env_file: 
      - ./.env 
    depends_on:
      mongo_db:
        condition: service_started
    ports: ["8002:8002"]
    volumes:
      - ./team_service:/app
    restart: unless-stopped
  
  # --- Task Service ---
  task_service:
    build: ./task_service
    container_name: task_service
    env_file:
      - ./.env  
    depends_on:
      mongo_db:
        condition: service_started
    ports: ["8003:8003"]
    volumes:
      - ./task_service:/app
    restart: unless-stopped

  # --- Frontend Service ---
  frontend_service:
    build:
      context: ./frontend_service
      target: build 
    volumes:
    - ./frontend_service:/app 
    - /app/node_modules 
    command: npm run dev -- --host 
    ports:
    - "5173:5173" # default port for vite

volumes:
  mysql_data:
  mongo_data:
  user_avatars: